services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env

    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
